#!/usr/bin/env bash
#
# scripts/db/provision-postgres-runbook.sh
#
# Echo-only runbook helper for provisioning the production PostgreSQL on
# Fly.io (cluster name = `instaedit-production`). Pure shell `echo` — no
# side effects, no network calls, no credentials generated — every line
# below is meant to be copy/pasted into an operator terminal that has
# `flyctl auth login` already done.
#
# This script exists because the "first provisioning" path has 4-5
# sites that must agree (cluster name, region, size, HA replicas, PITR
# window, pooler, password). Drift between those sites = an outage in
# disguise. The script pins every flag + every name + every command
# in ONE file so the operator (or a future audit) can verify by
# `diff ./scripts/db/provision-postgres-runbook.sh <what-was-run>`.
#
# ─── USAGE ──────────────────────────────────────────────────────────────
#   ./scripts/db/provision-postgres-runbook.sh              # print all
#   ./scripts/db/provision-postgres-runbook.sh --help      # this header
#   ./scripts/db/provision-postgres-runbook.sh --json      # machine-readable
#
# Exit codes:
#   0  always (the script does no I/O)
#
# ─── RISKS for the operator to internalise before they run ─────────────
# - R1: PRODUCTION DATA. `fly postgres create` is BILLABLE. The cluster
#   builds a hot PG15/16/17 on Fly's network. The cluster name + region
#   + size are the only knobs the operator can change without a
#   destructive recreate (Fly doesn't support online resize of cluster
#   NAME; can resize VM/volume).
# - R2: NAME. The spec locks the cluster name to `instaedit-production`.
#   Drift to `instaedit-pg` or `instaedit-prod` breaks downstream
#   automation (scripts/set-fly-secrets.sh docstring references the
#   cluster name).
# - R3: PASSWORD. The password generated by `openssl` is the ONLY
#   credential the operator controls end-to-end. Fly also generates a
#   one-time admin password internally but the application never uses
#   it (it uses the cluster user + the operator-provided password).
# - R4: PITR. PITR is enabled by default on Fly Postgres 14+, retention
#   7 days. Longer windows are configured via the Fly dashboard
#   (billing-tied).
# - R5: HA replicas=1. Cost-balanced. ONE standby replica that follows
#   the primary within ~1s; reader traffic can be routed to it via the
#   `?replica=true` switch (not used in beta). ZERO replicas = NO
#   failover, RPO = whatever the OS crash window is.
#
# ─── DESIGN RATIONALE per the choice made below ─────────────────────────
# - Region iad: matches `fly.toml primary_region` so both machines +
#   the Postgres replica live in the same Fly region for sub-ms latency.
# - VM size shared-cpu-1x / 1GB: matches the Fly app vCPU footprint
#   (the api+worker processes are also shared-cpu-1x/512MB per
#   `[vm]` in fly.toml). Postgres needs more headroom (1GB not 512MB)
#   because we're running back-ground workers + concurrent connections.
#   Upgrading to dedicated-cpu-1x is a Fly dashboard toggle, no re-create.
# - HA replicas=1: standby is a hot copy. Reading from it requires a
#   separate URL (`?replica=true` query param on flycast), not used in
#   beta. Cost delta: +1x the VM price.
# - Pooler: built-in PgBouncer. `--pg-bouncer-enabled=true` makes Fly
#   expose the pooler on a separate port (6432). The application talks
#   to the pooler (cheaper for short-lived bursts); migrations talk
#   DIRECT without going through PgBouncer (PgBouncer breaks DDL
#   transactions).
# - Volume size: intentionally OMITTED from this helper — Fly Postgres
#   default of 10 GB matches the baseline. Operators needing a bigger
#   initial volume should add `--volume-size NG` to the emitted
#   command AFTER reading the docs/DEPLOY.md §2 trade-off notes.
#
# ─── HEREDOC SAFETY NOTE ────────────────────────────────────────────────
# This script uses `<<EOF` (unquoted heredoc) for several blocks. The
# body IS subject to bash expansion — meaning `$(cmd)` would execute
# at heredoc read time and `$VAR` would be replaced by the variable value.
# We want the LITERAL output (so the operator can copy/paste), so every
# `$(...)` is ESCAPED as `\\$(...)` and every `$VAR` is ESCAPED as
# `\\$VAR`. Removing the backslashes from ANY escape = a side-effect
# (and is potentially a secret leak for `$(openssl ...)`). Future
# maintainers: prefer `<<'EOF'` (quoted heredoc) for new blocks; the
# unquoted pattern here is preserved only because the existing block
# structure is already locked-in by the 10-step walkthrough.
set -euo pipefail

# Names the runbook locks in. Don't change unless you also change
# scripts/set-fly-secrets.sh + fly.toml header + docs/PROVIDER_MATRIX.md.
CLUSTER_NAME="instaedit-production"
REGION="iad"
VM_SIZE="shared-cpu-1x"
VM_MEMORY="1gb"
HA_REPLICAS="1"
PG_VERSION="16"  # 14+ for PITR; 16 is the current Fly stable default.

MODE="text"
for arg in "$@"; do
    case "$arg" in
        --help|-h)
            sed -n '2,40p' "$0"
            exit 0
            ;;
        --json)
            MODE="json"
            ;;
        *)
            echo "❌ unknown arg: $arg" >&2
            exit 2
            ;;
    esac
done

print_block() {
    if [[ "$MODE" == "json" ]]; then
        python3 -c "import json,sys; json.dump(sys.stdin.read(), sys.stdout)" || cat
    else
        cat
    fi
}

# ─── STEP 1: generate the production password ────────────────────────────
cat <<EOF
── 1. Generate a 384-bit password for the PostgreSQL primary user ────
(The Fly Postgres cluster creates a default user with the same name as
the cluster. We set the password to a fresh 48-byte random value so
it is unguessable + unique across dev/staging/prod.)

    PROD_PG_PASSWORD="\\$(openssl rand -base64 48)"
    echo "\\$PROD_PG_PASSWORD"   # copy this into your password manager NOW
    # Format check: 64-char base64, no spaces, no leading ":"
    echo "\\$PROD_PG_PASSWORD" | wc -c    # must print 65 (64 chars + newline)

Vault entry template:
    instaedit-login/db-password/production = "\\$PROD_PG_PASSWORD"

EOF

# ─── STEP 2: pre-flight (operator-side, before flyctl) ───────────────────
cat <<EOF
── 2. Pre-flight (operator terminal) ──────────────────────────────────
    flyctl version          # must show >= 0.10
    flyctl auth whoami      # must show your org handle + email
    flyctl apps list | grep instaedit-login || echo "ERROR: app not found, run §2 of docs/DEPLOY.md first"

EOF

# ─── STEP 3: the canonical flyctl create command ────────────────────────
cat <<EOF
── 3. Create the production Postgres cluster ─────────────────────────
(Paste-in-one-line. The \\$PROD_PG_PASSWORD substitution is shell-side,
NOT a Fly-side flag, so the password never reaches Fly's metadata
service as a literal CLI arg.)

    PROD_PG_PASSWORD="\\$(openssl rand -base64 48)"
    flyctl postgres create \\\\
        --name ${CLUSTER_NAME} \\\\
        --region ${REGION} \\\\
        --vm-size ${VM_SIZE} \\\\
        --vm-memory ${VM_MEMORY} \\\\
        --initial-cluster-size ${HA_REPLICAS} \\\\
        --pg-bouncer-enabled=true \\\\
        --password "\\$PROD_PG_PASSWORD" \\\\
        --version ${PG_VERSION}
    # NOTE: --volume-size is intentionally NOT set here — Fly default of
    # 10 GB matches our baseline. Operators wanting more should add the
    # flag AFTER reading docs/DEPLOY.md §2 trade-off notes.

When the command completes (~3-5 min), Fly prints TWO connection strings:
  (a) DIRECT  : postgres://<user>:\\$PROD_PG_PASSWORD@${CLUSTER_NAME}.flycast:5432/<db>?sslmode=require
  (b) POOLED  : postgres://<user>:\\$PROD_PG_PASSWORD@${CLUSTER_NAME}-bouncer.flycast:5432/<db>?sslmode=require&pgbouncer=true

Save BOTH URLs into your password manager under these keys:
    instaedit-login/database-url/production/direct = <DIRECT>
    instaedit-login/database-url/production/pooled = <POOLED>

NOTE the missing <db>: Fly Postgres creates a default database with the
SAME NAME as the cluster (i.e. this script names the cluster
"${CLUSTER_NAME}" so the database is also "${CLUSTER_NAME}" inside
the cluster). Verify after connect:
    psql "\\$DATABASE_URL_DIRECT" -c "SELECT current_database();"
#    expected: current_database = ${CLUSTER_NAME}

EOF

# ─── STEP 4: enable PITR + verify backup cadence ─────────────────────────
cat <<'EOF'
── 4. Enable PITR + verify backups (Fly dashboard) ────────────────────
PITR is enabled by default on Fly Postgres 14+. The retention window
is 7 days by default, configurable to 14 days via dashboard:

    https://fly.io/dashboard/<YOUR-ORG>/postgres/<CLUSTER_NAME>/backups

Click "Point-in-time recovery" → set retention to 14 days (covers a
two-week incident window + a long weekend). Base backups are taken
daily at 04:00 UTC; verify the first one completed ~24h after create.

EOF

# ─── STEP 5: attach the pooler URL to the Fly app ───────────────────────
cat <<EOF
── 5. Attach the pooled DATABASE_URL as a Fly secret ─────────────────
The POOLED URL goes to both api and worker (they run on the SAME
machine so a single env var is fine). The DIRECT URL is reserved
for emergency/migrations only (NOT a regular app secret).

    DATABASE_URL_DIRECT="\\$(cat ~/.fly-secrets-database-url-direct.txt)"   # pull from your manager
    DATABASE_URL_POOLED="\\$(cat ~/.fly-secrets-database-url-pooled.txt)"   # pull from your manager

    flyctl secrets set --app instaedit-login --stage \\\\
        DATABASE_URL="\\$DATABASE_URL_POOLED"

For DR purposes, also stage the DIRECT URL under a different env name
(scripts/required-fly-secrets.txt does NOT list it — it stays out of
the standard contracts because migrations run via release_command and
don't need it as a named secret):

    flyctl secrets set --app instaedit-login --stage \\\\
        DATABASE_URL_DIRECT="\\$DATABASE_URL_DIRECT" \\\\
        DATABASE_URL_POOL_ADMIN="\\$DATABASE_URL_DIRECT"

The app never reads DATABASE_URL_DIRECT (only the operator's emergency
runbook uses it via \`fly ssh --app instaedit-login --command "psql ..."\`).

EOF

# ─── STEP 6: smoke check from outside Fly (your laptop) ────────────────
cat <<'EOF'
── 6. Smoke check the new cluster from your laptop ───────────────────
Before the next `make fly-deploy`, confirm the cluster is reachable
+ SSL is on + the canary tables are empty (migrations will create them):

    DATABASE_URL=<POOLED-URL-FROM-PASSWORDMANAGER> \\
        ./scripts/db/check-postgres-health.sh

Expected output (truncated):
    ✓ sslmode=require
    ✓ SELECT version() = PostgreSQL 16.x
    ✓ connection latency: 23ms (5x50ms)
    ✓ 0 canary tables present (pre-migration)
    ✓ cluster is empty

EOF

# ─── STEP 7: first migration deploy ────────────────────────────────────
cat <<'EOF'
── 7. First migration deploy (via make fly-deploy) ───────────────────
After smoke check is green:

    make fly-deploy

The Makefile target `fly-deploy` invokes `flyctl deploy` which runs
the Dockerfile's release_command = `./migrate` as a fresh ephemeral
machine BEFORE any api/worker VM is rolled out. The release_command
exits 0 iff migrations applied cleanly. If it exits non-zero, the
new app version is NOT deployed; you keep the (empty) cluster and
can retry.

After `make fly-deploy` succeeds, re-run the smoke check:
    DATABASE_URL=<POOLED-URL> \\
        ./scripts/db/check-postgres-health.sh

Expected output change: "9 canary tables present (post-migration)".

EOF

# ─── STEP 8: snapshot the cluster identity into `.env.production` ──────
cat <<EOF
── 8. Snapshot into .env.production (operator-only local file) ───────
The DATABASE_URL secret on Fly is set; now write the pool URL into
your local .env.production so subsequent \`make fly-secrets --apply\`
overwrites cleanly without drift:

    cp .env.example .env.production
    # Open .env.production in \\$EDITOR; locate the line:
    #   DATABASE_URL=
    # Fill it with the POOLED URL. The python parser
    # (scripts/_parse_envfile.py) will assert sslmode is not 'disable'
    # and reject the file with a hard error otherwise.

Sanity check the file:
    git check-ignore .env.production || echo "WARN: .env.production is NOT gitignored"
    make fly-secrets-dry-run

EOF

# ─── STEP 9: schedule restore drill ─────────────────────────────────────
cat <<EOF
── 9. Schedule the FIRST restore drill ──────────────────────────────
Run within 24h of step 7 (after at least one migration cycle):

    SERVICES_PROD_DSN="\\$(cat ~/.fly-secrets-database-url-pooled.txt)" \\\\
    FORK_DSN="<FORK_URI_PRINTED_BY_FLY_BELOW>" \\\\
        ./scripts/db/production-restore-drill.sh

The fork URI is generated by:
    FLY_TS="\\$(date -u +%Y%m%dT%H%M%SZ)"
    FLY_FORK_NAME="instaedit-restore-drill-\\$FLY_TS"
    flyctl postgres fork \\\\
        --from ${CLUSTER_NAME} \\\\
        --to "\\$FLY_FORK_NAME" \\\\
        --region ${REGION}
    # Copy the printed POOLED URL of the new fork into \\$FORK_DSN.

DO NOT destroy the fork in the same step. The script prints the
\`fly postgres destroy\` command for the operator to run AFTER
the drill report is saved into ops/restore-drill-\$FLY_TS.md.

EOF

# ─── STEP 10: cross-reference the deliverables ──────────────────────────
cat <<EOF
── 10. Operator checklist (paste into your runbook) ─────────────────
[ ] \\$PROD_PG_PASSWORD saved to password manager (384-bit base64)
[ ] DIRECT + POOLED URLs saved to password manager (2 entries)
[ ] fly postgres create exited 0, both URLs printed
[ ] dashboard PITR retention bumped to 14 days
[ ] DATABASE_URL secret set on instaedit-login (verify: \`make fly-secrets-verify\`)
[ ] scripts/db/check-postgres-health.sh: sslmode ✓ + version ✓ + 0 tables pre-mig
[ ] make fly-deploy: release_command exited 0
[ ] scripts/db/check-postgres-health.sh: 9 canary tables post-mig
[ ] make fly-secrets-dry-run: 15/15 secrets pass
[ ] restore drill scheduled (within 24h), report saved to ops/

After ALL 10 boxes ticked, the cluster is operational.

EOF
