package api

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/Marcuss-ops/InstaeditLogin/internal/models"
	"github.com/Marcuss-ops/InstaeditLogin/internal/services"
)

func TestHandleCallback_Facebook_SavesPageAccessToken(t *testing.T) {
	const userLongLivedToken = "user-long-lived-token"
	pages := []*services.DiscoveredAccount{
		{
			Profile: models.PlatformProfile{PlatformUserID: "page-1", Username: "Page One"},
			SupplementalTokens: []*models.TokenData{
				{AccessToken: "page-token-1", TokenType: models.TokenTypePageAccess, ExpiresIn: 60 * 60 * 24 * 365 * 10, Scopes: []string{"pages_manage_posts", "pages_read_engagement", "pages_show_list"}},
			},
		},
		{
			Profile: models.PlatformProfile{PlatformUserID: "page-2", Username: "Page Two"},
			SupplementalTokens: []*models.TokenData{
				{AccessToken: "page-token-2", TokenType: models.TokenTypePageAccess, ExpiresIn: 60 * 60 * 24 * 365 * 10, Scopes: []string{"pages_manage_posts", "pages_read_engagement", "pages_show_list"}},
			},
		},
	}

	svc := &mockDiscoverableProvider{
		mockProvider: mockProvider{
			platform: "facebook",
			handleCallback: func(ctx context.Context, state, code string) (*models.PlatformProfile, *models.TokenData, error) {
				return &models.PlatformProfile{PlatformUserID: "fb-user-123", Username: "FB User"}, &models.TokenData{
					AccessToken: userLongLivedToken,
					TokenType:   models.TokenTypeLongLived,
					ExpiresIn:   5184000,
				}, nil
			},
		},
		discoverFn: func(ctx context.Context, accessToken, platformUserID string) ([]*services.DiscoveredAccount, error) {
			if accessToken != userLongLivedToken {
				t.Errorf("DiscoverAccounts accessToken: want %q, got %q", userLongLivedToken, accessToken)
			}
			return pages, nil
		},
	}

	var attachCount int
	store := &mockUserStore{
		attachFn: func(userID int64, profile *models.PlatformProfile, platform string) (*models.PlatformAccount, error) {
			attachCount++
			return &models.PlatformAccount{
				ID:             int64(10 + attachCount),
				UserID:         userID,
				Platform:       platform,
				PlatformUserID: profile.PlatformUserID,
				Username:       profile.Username,
			}, nil
		},
	}
	// Task 1/10 — atomic OAuth finalize: token-write visibility is
	// owned by the fakeChannelAuthorizer (independent audit trail
	// in tokenWrites). The vault mock is no longer in this code
	// path's call chain so we don't even need WithCredentialVault
	// override for the cipher count.
	authorizer := &fakeChannelAuthorizer{}
	r := newTestRouter(svc, store, "", WithChannelAuthorizer(authorizer))

	req := httptest.NewRequest(http.MethodGet, "/api/v1/auth/facebook/callback?code=abc&state=test-state", nil)
	setOAuthStateCookieForTest(req, "facebook", "test-state")
	w := httptest.NewRecorder()
	withBearerJWT(t, req, 1)
	r.Setup().ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("want 200, got %d: %s", w.Code, w.Body.String())
	}

	// Expect 4 token writes: page token + user token for each of the 2 pages.
	// The atomic AuthorizeChannel call records both principal
	// (user long-lived) AND supplemental (page access) tokens in the
	// SAME call — same surface contract as the legacy non-atomic
	// path that issued two separate r.vault.Save calls per page.
	if authorizer.tokenWriteCount() != 4 {
		t.Fatalf("want 4 token writes (2 page + 2 user), got %d: %+v", authorizer.tokenWriteCount(), authorizer.tokenWrites)
	}
	// Build a map keyed by (accountID, tokenType) to avoid relying on save order.
	writtenByType := make(map[int64]map[string]string)
	authorizer.mu.Lock()
	for _, w := range authorizer.tokenWrites {
		if writtenByType[w.AccountID] == nil {
			writtenByType[w.AccountID] = make(map[string]string)
		}
		writtenByType[w.AccountID][w.TokenType] = w.AccessToken
	}
	authorizer.mu.Unlock()
	for _, p := range pages {
		// The account IDs are generated by attachFn as 10, 11, ...
		// SupplementalTokens carry the page token — find by matching
		// the AccessToken from SupplementalTokens[0].
		var foundID int64
		expectedPageToken := p.SupplementalTokens[0].AccessToken
		for id, tokens := range writtenByType {
			if tokens[models.TokenTypePageAccess] == expectedPageToken {
				foundID = id
				break
			}
		}
		if foundID == 0 {
			t.Fatalf("missing page token save for page %s", p.Profile.PlatformUserID)
		}
		if writtenByType[foundID][models.TokenTypePageAccess] != expectedPageToken {
			t.Errorf("page %s: want page token %q, got %q", p.Profile.PlatformUserID, expectedPageToken, writtenByType[foundID][models.TokenTypePageAccess])
		}
		if writtenByType[foundID][models.TokenTypeLongLived] != userLongLivedToken {
			t.Errorf("page %s: want user token %q, got %q", p.Profile.PlatformUserID, userLongLivedToken, writtenByType[foundID][models.TokenTypeLongLived])
		}
	}
}

func TestHandleCallback_YouTube_OneChannel_OneSave(t *testing.T) {
	const bearerToken = "yt-bearer-token-1"
	channels := []*services.DiscoveredAccount{
		{Profile: models.PlatformProfile{PlatformUserID: "UCsoloChannel", Username: "Solo Channel"}},
	}
	svc := &mockDiscoverableProvider{
		mockProvider: mockProvider{
			platform: "youtube",
			handleCallback: func(ctx context.Context, state, code string) (*models.PlatformProfile, *models.TokenData, error) {
				return &models.PlatformProfile{PlatformUserID: "g-acc-1", Username: "G Acc"}, &models.TokenData{
					AccessToken: bearerToken, TokenType: models.TokenTypeBearer, ExpiresIn: 3600,
				}, nil
			},
		},
		discoverFn: func(ctx context.Context, accessToken, platformUserID string) ([]*services.DiscoveredAccount, error) {
			return channels, nil
		},
	}
	type saveCall struct {
		accountID int64
		token     string
	}
	store := &mockUserStore{
		attachFn: func(userID int64, profile *models.PlatformProfile, platform string) (*models.PlatformAccount, error) {
			return &models.PlatformAccount{
				ID: 10, UserID: userID, Platform: platform,
				PlatformUserID: profile.PlatformUserID, Username: profile.Username,
			}, nil
		},
	}
	// Task 1/10 — atomically via r.authorizer.AuthorizeChannel.
	// tokenWrites is the independent audit trail in the fake.
	authorizer := &fakeChannelAuthorizer{}
	r := newTestRouter(svc, store, "", WithChannelAuthorizer(authorizer))

	req := httptest.NewRequest(http.MethodGet, "/api/v1/auth/youtube/callback?code=abc&state=test-state", nil)
	setOAuthStateCookieForTest(req, "youtube", "test-state")
	w := httptest.NewRecorder()
	withBearerJWT(t, req, 1)
	r.Setup().ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("want 200, got %d: %s", w.Code, w.Body.String())
	}
	if authorizer.tokenWriteCount() != 1 {
		t.Fatalf("tokenWrites must be exactly 1 (single channel, atomic), got %d: %+v", authorizer.tokenWriteCount(), authorizer.tokenWrites)
	}
	w0 := authorizer.tokenWrites[0]
	if w0.AccountID != 10 || w0.AccessToken != bearerToken {
		t.Errorf("tokenWrites[0]: want (accountID=10, access=%q), got %+v", bearerToken, w0)
	}
}

func TestHandleCallback_YouTube_MultipleChannels_NoExpected_Conflict(t *testing.T) {
	channels := []*services.DiscoveredAccount{
		{Profile: models.PlatformProfile{PlatformUserID: "UCaaaaaaaaaaaaaaaaaaaaa1", Username: "Channel A"}},
		{Profile: models.PlatformProfile{PlatformUserID: "UCaaaaaaaaaaaaaaaaaaaaa2", Username: "Channel B"}},
	}
	svc := &mockDiscoverableProvider{
		mockProvider: mockProvider{
			platform: "youtube",
			handleCallback: func(ctx context.Context, state, code string) (*models.PlatformProfile, *models.TokenData, error) {
				return &models.PlatformProfile{PlatformUserID: "g-acc", Username: "G"}, &models.TokenData{
					AccessToken: "bearer", TokenType: models.TokenTypeBearer, ExpiresIn: 3600,
				}, nil
			},
		},
		discoverFn: func(ctx context.Context, accessToken, platformUserID string) ([]*services.DiscoveredAccount, error) {
			return channels, nil
		},
	}
	authorizer := &fakeChannelAuthorizer{}
	store := &mockUserStore{
		attachFn: func(userID int64, profile *models.PlatformProfile, platform string) (*models.PlatformAccount, error) {
			// attachFn must NOT be called when discovery is ambiguous —
			// if it is, the bug is back.
			return &models.PlatformAccount{
				ID: 10, UserID: userID, Platform: platform,
				PlatformUserID: profile.PlatformUserID,
			}, nil
		},
	}
	r := newTestRouter(svc, store, "", WithChannelAuthorizer(authorizer))

	req := httptest.NewRequest(http.MethodGet, "/api/v1/auth/youtube/callback?code=abc&state=test-state", nil)
	setOAuthStateCookieForTest(req, "youtube", "test-state")
	w := httptest.NewRecorder()
	withBearerJWT(t, req, 1)
	r.Setup().ServeHTTP(w, req)

	if w.Code != http.StatusConflict {
		t.Fatalf("ambiguous grant: want 409 Conflict, got %d: %s", w.Code, w.Body.String())
	}
	if authorizer.tokenWriteCount() != 0 {
		t.Fatalf("ambiguous grant must NOT write tokens on ANY channel; got %d write(s)", authorizer.tokenWriteCount())
	}
	if authorizer.authorizeCalls.Load() != 0 {
		t.Fatalf("ambiguous grant must NOT invoke AuthorizeChannel at all (channels.list guard rejects pre-tx); got %d call(s)", authorizer.authorizeCalls.Load())
	}
	if !strings.Contains(w.Body.String(), "ambiguous") {
		t.Errorf("response body should explain the ambiguity, got %q", w.Body.String())
	}
}

func TestHandleCallback_YouTube_MultipleChannels_ExpectedMatches_OneSave(t *testing.T) {
	const expectedID = "UCaaaaaaaaaaaaaaaaaaaaa2"
	channels := []*services.DiscoveredAccount{
		{Profile: models.PlatformProfile{PlatformUserID: "UCaaaaaaaaaaaaaaaaaaaaa1", Username: "Channel A"}},
		{Profile: models.PlatformProfile{PlatformUserID: expectedID, Username: "Channel B"}},
		{Profile: models.PlatformProfile{PlatformUserID: "UCaaaaaaaaaaaaaaaaaaaaa3", Username: "Channel C"}},
	}
	svc := &mockDiscoverableProvider{
		mockProvider: mockProvider{
			platform: "youtube",
			handleCallback: func(ctx context.Context, state, code string) (*models.PlatformProfile, *models.TokenData, error) {
				return &models.PlatformProfile{PlatformUserID: "g-acc", Username: "G"}, &models.TokenData{
					AccessToken: "yt-bearer", TokenType: models.TokenTypeBearer, ExpiresIn: 3600,
				}, nil
			},
		},
		discoverFn: func(ctx context.Context, accessToken, platformUserID string) ([]*services.DiscoveredAccount, error) {
			return channels, nil
		},
	}
	// Fixed account-ID <-> channel-ID mapping so vault.Save can be
	// reverse-traced to the channel it was attached to.
	accountIDsByChannel := map[string]int64{
		"UCaaaaaaaaaaaaaaaaaaaaa1": 101,
		expectedID:                 102,
		"UCaaaaaaaaaaaaaaaaaaaaa3": 103,
	}
	attachedChannels := []string{}
	store := &mockUserStore{
		attachFn: func(userID int64, profile *models.PlatformProfile, platform string) (*models.PlatformAccount, error) {
			id, ok := accountIDsByChannel[profile.PlatformUserID]
			if !ok {
				return nil, fmt.Errorf("unexpected channel %q in attachFn", profile.PlatformUserID)
			}
			attachedChannels = append(attachedChannels, profile.PlatformUserID)
			return &models.PlatformAccount{
				ID: id, UserID: userID, Platform: platform,
				PlatformUserID: profile.PlatformUserID, Username: profile.Username,
			}, nil
		},
	}
	authorizer := &fakeChannelAuthorizer{}
	r := newTestRouter(svc, store, "", WithChannelAuthorizer(authorizer))

	req := httptest.NewRequest(http.MethodGet, "/api/v1/auth/youtube/callback?code=abc&state=test-state", nil)
	setOAuthStateCookieForTest(req, "youtube", "test-state")
	setOAuthExpectedChannelCookieForTest(req, "youtube", "test-state", expectedID)
	w := httptest.NewRecorder()
	withBearerJWT(t, req, 1)
	r.Setup().ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("want 200, got %d: %s", w.Code, w.Body.String())
	}
	if len(attachedChannels) != 1 {
		t.Fatalf("attachFn must be called exactly once (only expected channel); got %d calls for channels %v", len(attachedChannels), attachedChannels)
	}
	if attachedChannels[0] != expectedID {
		t.Errorf("attachFn must target expected channel %q; got %q", expectedID, attachedChannels[0])
	}
	if authorizer.tokenWriteCount() != 1 {
		t.Fatalf("tokenWrites must be exactly once; got %d: %+v", authorizer.tokenWriteCount(), authorizer.tokenWrites)
	}
	w0 := authorizer.tokenWrites[0]
	if w0.AccountID != accountIDsByChannel[expectedID] {
		t.Errorf("tokenWrites[0] accountID: want %d (channel %q), got %d", accountIDsByChannel[expectedID], expectedID, w0.AccountID)
	}
	if w0.AccessToken != "yt-bearer" {
		t.Errorf("tokenWrites[0] access: want yt-bearer, got %q", w0.AccessToken)
	}
}

func TestHandleCallback_YouTube_ExpectedNoMatch_Conflict(t *testing.T) {
	channels := []*services.DiscoveredAccount{
		{Profile: models.PlatformProfile{PlatformUserID: "UCaaaaaaaaaaaaaaaaaaaaa1", Username: "Channel A"}},
	}
	svc := &mockDiscoverableProvider{
		mockProvider: mockProvider{
			platform: "youtube",
			handleCallback: func(ctx context.Context, state, code string) (*models.PlatformProfile, *models.TokenData, error) {
				return &models.PlatformProfile{PlatformUserID: "g-acc", Username: "G"}, &models.TokenData{
					AccessToken: "bearer", TokenType: models.TokenTypeBearer, ExpiresIn: 3600,
				}, nil
			},
		},
		discoverFn: func(ctx context.Context, accessToken, platformUserID string) ([]*services.DiscoveredAccount, error) {
			return channels, nil
		},
	}
	authorizer := &fakeChannelAuthorizer{}
	store := &mockUserStore{
		attachFn: func(userID int64, profile *models.PlatformProfile, platform string) (*models.PlatformAccount, error) {
			return &models.PlatformAccount{ID: 10, UserID: userID, Platform: platform, PlatformUserID: profile.PlatformUserID}, nil
		},
	}
	r := newTestRouter(svc, store, "", WithChannelAuthorizer(authorizer))

	req := httptest.NewRequest(http.MethodGet, "/api/v1/auth/youtube/callback?code=abc&state=test-state", nil)
	setOAuthStateCookieForTest(req, "youtube", "test-state")
	setOAuthExpectedChannelCookieForTest(req, "youtube", "test-state", "UCaaaaaaaaaaaaaaaaaaaaaZ")
	w := httptest.NewRecorder()
	withBearerJWT(t, req, 1)
	r.Setup().ServeHTTP(w, req)

	if w.Code != http.StatusConflict {
		t.Fatalf("mismatched expected: want 409, got %d: %s", w.Code, w.Body.String())
	}
	if authorizer.tokenWriteCount() != 0 {
		t.Fatalf("mismatch must NOT write tokens; got %d write(s)", authorizer.tokenWriteCount())
	}
	if authorizer.authorizeCalls.Load() != 0 {
		t.Fatalf("mismatch must NOT invoke AuthorizeChannel (channels.list guard rejects pre-tx); got %d call(s)", authorizer.authorizeCalls.Load())
	}
	if !strings.Contains(w.Body.String(), "does not match expected channel") {
		t.Errorf("response body should reference the mismatch, got %q", w.Body.String())
	}
}
