package repository

import (
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/Marcuss-ops/InstaeditLogin/internal/models"
)

// ErrMediaAssetSHARequired is the typed sentinel returned by
// MarkReady when the caller passes an empty SHA. Task 6/10 raises
// this from a runtime guard (the schema NOT NULL constraint added by
// migration 056 was insufficient because ” is NULL-free and passes
// the schema check — the repo contract MUST refuse empty as a
// defence-in-depth). errors.Is(err, ErrMediaAssetSHARequired) lets
// callers (HTTP handlers, worker tick) distinguish the empty-SHA
// failure from generic repo errors so the operator-facing error
// message guides the fix (re-upload with explicit hash at presign,
// or rely on the streaming-compute path that always stamps a 64-hex
// string from the artifactVerifyReader).
var ErrMediaAssetSHARequired = errors.New("media asset sha256 is required (Task 6/10 enforcement; empty SHA was the legacy 'no SHA recorded' sentinel and is no longer accepted on fresh MarkReady calls)")

// MediaAssetRepository persists Taglio 3.2 media_assets rows. The
// repository is the single owner of the table — handlers, workers, and
// the publish flow go through this struct rather than touching the
// `media_assets` table directly.
type MediaAssetRepository struct {
	db *sql.DB
}

// NewMediaAssetRepository wires the repo. The caller owns db lifetime
// (typically database.Connect + defer db.Close() in main.go).
func NewMediaAssetRepository(db *sql.DB) *MediaAssetRepository {
	return &MediaAssetRepository{db: db}
}

// Create inserts a new media_assets row in `pending` state. The
// caller must pre-set UploadKey, ContentType, SizeBytes, UserID, and
// ExpiresAt. ID is generated by the database (gen_random_uuid); on
// success the struct's ID/CreatedAt/UpdatedAt fields are populated
// from the RETURNING clause.
//
// Default status is `pending` if the caller left it empty.
func (r *MediaAssetRepository) Create(asset *models.MediaAsset) error {
	if asset.Status == "" {
		asset.Status = models.MediaAssetStatusPending
	}
	if !asset.Status.IsValid() {
		return fmt.Errorf("invalid media asset status: %q", asset.Status)
	}
	err := r.db.QueryRow(
		`INSERT INTO media_assets
		   (user_id, upload_key, content_type, size_bytes, status, sha256, expires_at)
		 VALUES ($1, $2, $3, $4, $5, $6, $7)
		 RETURNING id, created_at, updated_at`,
		asset.UserID, asset.UploadKey, asset.ContentType, asset.SizeBytes,
		string(asset.Status), asset.SHA256, asset.ExpiresAt,
	).Scan(&asset.ID, &asset.CreatedAt, &asset.UpdatedAt)
	if err != nil {
		return fmt.Errorf("failed to create media asset: %w", err)
	}
	return nil
}

// FindByID returns the asset for the given UUID. Matches the codebase
// convention: (nil, nil) on not-found, no sql.ErrNoRows leaking out.
func (r *MediaAssetRepository) FindByID(id string) (*models.MediaAsset, error) {
	asset := &models.MediaAsset{}
	err := r.db.QueryRow(
		`SELECT id, user_id, upload_key, content_type, size_bytes, status,
		        COALESCE(sha256, '') AS sha256,
		        COALESCE(error_message, '') AS error_message,
		        expires_at, created_at, updated_at
		 FROM media_assets WHERE id = $1`, id,
	).Scan(
		&asset.ID, &asset.UserID, &asset.UploadKey, &asset.ContentType,
		&asset.SizeBytes, &asset.Status, &asset.SHA256, &asset.ErrorMessage,
		&asset.ExpiresAt, &asset.CreatedAt, &asset.UpdatedAt,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("failed to find media asset: %w", err)
	}
	return asset, nil
}

// MarkReady transitions an asset to `ready` after the /complete
// handler HEAD-verified the S3 object (or after the worker's
// streaming-compute path stamped a non-empty local SHA via the
// artifactVerifyReader). Task 6/10 contract:
//   - sha256 MUST be a 64-char lowercase hex string. Empty string is
//     REJECTED at the repo level via ErrMediaAssetSHARequired —
//     defence-in-depth on top of migration 056's NOT NULL constraint
//     (which only blocks SQL NULL, not the empty-string legacy
//     sentinel).
//   - sizeBytes + contentType are the server-measured values from
//     the upstream verification path (HEAD on the /complete handler;
//     streaming-tee-then-upload on the worker + drive import paths).
//     Both are required for the schema invariant, the /complete
//     handler must assert equality with the presign-declared values
//     BEFORE invoking MarkReady, and the worker streaming verify
//     must assert equality with the ArtifactVerificationPolicy
//     BEFORE invoking MarkReady. MarkReady itself does NOT
//     re-verify (the value was already verified at the call site;
//     re-verifying here would be redundant + would double the bytes
//     read on large uploads).
func (r *MediaAssetRepository) MarkReady(id, sha256 string, sizeBytes int64, contentType string) error {
	// Task 6/10 — runtime guard against the legacy empty-SHA
	// sentinel. Cheap O(1) reject in the hot path; the same value
	// would have been silently preserved by the prior
	// COALESCE(NULLIF($2, ''), sha256) SQL — a behaviour that
	// contradicts the user's spec ('MAI più stringa SHA vuota')
	// and the migration 056 NOT NULL intent. Today every production
	// caller wrapping the byte stream in an artifactVerifyReader
	// (Drive import, worker pull-path) passes
	// verifyReader.ActualSHA256Hex() which is always a non-empty
	// 64-hex; the /complete handler is the only path that could
	// historically have passed empty — handleCompleteMedia is
	// updated (Task 6/10) to reject empty SHA upfront with a 400
	// instead of letting the value reach MarkReady.
	if sha256 == "" {
		return fmt.Errorf("%w: media asset id=%s", ErrMediaAssetSHARequired, id)
	}
	now := time.Now()
	// SQL simplified: removed `COALESCE(NULLIF($2, ''), sha256)`
	// because the runtime guard above guarantees $2 is non-empty —
	// the COALESCE would be unreachable dead-code-by-condition.
	// Direct assignment makes the contract obvious in the diff
	// future readers will see (status='ready' implies a real SHA
	// was written, not a 'preserve legacy empty' gotcha).
	res, err := r.db.Exec(
		`UPDATE media_assets
		    SET status = $1, sha256 = $2,
		        size_bytes = $3, content_type = $4, error_message = '', updated_at = $5
		  WHERE id = $6`,
		string(models.MediaAssetStatusReady), sha256, sizeBytes, contentType, now, id,
	)
	if err != nil {
		return fmt.Errorf("failed to mark media asset ready: %w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("%w: media asset id=%s", ErrMediaAssetNotFound, id)
	}
	return nil
}

// MarkFailed transitions an asset to `failed` and records the reason.
// The /complete handler uses this when S3 HEAD returns 404, when the
// size/content-type don't match, or on any verification error.
func (r *MediaAssetRepository) MarkFailed(id, reason string) error {
	now := time.Now()
	res, err := r.db.Exec(
		`UPDATE media_assets
		    SET status = $1, error_message = $2, updated_at = $3
		  WHERE id = $4`,
		string(models.MediaAssetStatusFailed), reason, now, id,
	)
	if err != nil {
		return fmt.Errorf("failed to mark media asset failed: %w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("%w: media asset id=%s", ErrMediaAssetNotFound, id)
	}
	return nil
}

// MarkFailedWithReason is the diagnose-friendly variant of MarkFailed:
// the caller passes the underlying error (`cause`) so the helper can
// log it alongside the persist failure. The historical pattern was
// `_ = store.MarkFailed(id, err.Error())` — silent on second-failure,
// meaning an operator who noticed the original error rarely noticed
// that the failure-of-the-failure also failed. Centralising the
// "failure of the failure" log here means every "I tried to record
// failure" path emits one structured slog line.
//
// `cause` may be nil (e.g. when the caller shapes the reason itself);
// it's emitted only when non-nil. Returns the underlying persist
// error so callers that want to take further action (e.g. escalate
// via metric) can do so.
func (r *MediaAssetRepository) MarkFailedWithReason(id, reason string, cause error) error {
	err := r.MarkFailed(id, reason)
	if err != nil {
		slog.Error("media: failed to persist MarkFailed",
			"asset_id", id,
			"reason", reason,
			"cause", cause,
			"mark_err", err,
		)
	}
	return err
}

// MarkExpired is used by the cleanup pass that transitions any
// status=pending assets whose expires_at < NOW() to status=expired.
// Returns the number of rows affected.
func (r *MediaAssetRepository) MarkExpired(now time.Time) (int64, error) {
	res, err := r.db.Exec(
		`UPDATE media_assets
		    SET status = $1, updated_at = $2
		  WHERE status = $3 AND expires_at < $4`,
		string(models.MediaAssetStatusExpired), now,
		string(models.MediaAssetStatusPending), now,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to mark media assets expired: %w", err)
	}
	n, _ := res.RowsAffected()
	return n, nil
}
