package repository

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/lib/pq"

	"github.com/Marcuss-ops/InstaeditLogin/internal/models"
)

// ErrMediaAssetSHARequired is the typed sentinel returned by
// MarkReady when the caller passes an empty SHA. Task 6/10 raises
// this from a runtime guard (the schema NOT NULL constraint added by
// migration 056 was insufficient because ” is NULL-free and passes
// the schema check — the repo contract MUST refuse empty as a
// defence-in-depth). errors.Is(err, ErrMediaAssetSHARequired) lets
// callers (HTTP handlers, worker tick) distinguish the empty-SHA
// failure from generic repo errors so the operator-facing error
// message guides the fix (re-upload with explicit hash at presign,
// or rely on the streaming-compute path that always stamps a 64-hex
// string from the artifactVerifyReader).
var ErrMediaAssetSHARequired = errors.New("media asset sha256 is required (Task 6/10 enforcement; empty SHA was the legacy 'no SHA recorded' sentinel and is no longer accepted on fresh MarkReady calls)")

// MediaAssetRepository persists Taglio 3.2 media_assets rows. The
// repository is the single owner of the table — handlers, workers, and
// the publish flow go through this struct rather than touching the
// `media_assets` table directly.
type MediaAssetRepository struct {
	db *sql.DB
}

// NewMediaAssetRepository wires the repo. The caller owns db lifetime
// (typically database.Connect + defer db.Close() in main.go).
func NewMediaAssetRepository(db *sql.DB) *MediaAssetRepository {
	return &MediaAssetRepository{db: db}
}

// Create inserts a new media_assets row in `pending` state. The
// caller must pre-set UploadKey, ContentType, SizeBytes, UserID, and
// ExpiresAt. ID is generated by the database (gen_random_uuid); on
// success the struct's ID/CreatedAt/UpdatedAt fields are populated
// from the RETURNING clause.
//
// Default status is `pending` if the caller left it empty.
func (r *MediaAssetRepository) Create(asset *models.MediaAsset) error {
	if asset.Status == "" {
		asset.Status = models.MediaAssetStatusPending
	}
	if !asset.Status.IsValid() {
		return fmt.Errorf("invalid media asset status: %q", asset.Status)
	}
	err := r.db.QueryRow(
		`INSERT INTO media_assets
		   (user_id, upload_key, bucket, content_type, size_bytes, status, sha256, expires_at)
		 VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		 RETURNING id, created_at, updated_at`,
		asset.UserID, asset.UploadKey, asset.Bucket, asset.ContentType, asset.SizeBytes,
		string(asset.Status), asset.SHA256, asset.ExpiresAt,
	).Scan(&asset.ID, &asset.CreatedAt, &asset.UpdatedAt)
	if err != nil {
		return fmt.Errorf("failed to create media asset: %w", err)
	}
	return nil
}

// mediaAssetColumns is the full select list including the ffprobe
// columns (migration 092). Probe fields are scanned into the pointer
// fields directly (NULL → nil).
const mediaAssetColumns = `id, user_id, upload_key, bucket, content_type, size_bytes, status,
COALESCE(sha256, '') AS sha256, COALESCE(error_message, '') AS error_message,
expires_at, created_at, updated_at,
duration_seconds, width, height, fps, has_audio, video_codec, audio_codec, probed_at`

// FindByID returns the asset for the given UUID. Matches the codebase
// convention: (nil, nil) on not-found, no sql.ErrNoRows leaking out.
func scanMediaAsset(row interface{ Scan(...any) error }) (*models.MediaAsset, error) {
	asset := &models.MediaAsset{}
	err := row.Scan(
		&asset.ID, &asset.UserID, &asset.UploadKey, &asset.Bucket, &asset.ContentType,
		&asset.SizeBytes, &asset.Status, &asset.SHA256, &asset.ErrorMessage,
		&asset.ExpiresAt, &asset.CreatedAt, &asset.UpdatedAt,
		&asset.DurationSeconds, &asset.Width, &asset.Height, &asset.FPS, &asset.HasAudio,
		&asset.VideoCodec, &asset.AudioCodec, &asset.ProbedAt,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return asset, nil
}

func (r *MediaAssetRepository) FindByID(id string) (*models.MediaAsset, error) {
	asset, err := scanMediaAsset(r.db.QueryRow(
		`SELECT `+mediaAssetColumns+`
		 FROM media_assets WHERE id = $1`, id,
	))
	if err != nil {
		return nil, fmt.Errorf("failed to find media asset by id: %w", err)
	}
	return asset, nil
}

// ListReadyByUser returns the caller's ready, non-expired media assets
// newest-first, bounded by limit. Used by the Media Library endpoint
// (GET /api/v1/media) and the live wizard's step 3. A partial index on
// (user_id, status, created_at DESC) keeps the scan cheap.
func (r *MediaAssetRepository) ListReadyByUser(ctx context.Context, userID int64, limit int) ([]models.MediaAsset, error) {
	if userID <= 0 {
		return nil, fmt.Errorf("list media assets: invalid user id %d", userID)
	}
	if limit <= 0 || limit > 500 {
		limit = 100
	}
	rows, err := r.db.QueryContext(ctx,
		`SELECT `+mediaAssetColumns+`
		 FROM media_assets
		 WHERE user_id = $1 AND status = $2 AND expires_at > NOW()
		 ORDER BY created_at DESC, id
		 LIMIT $3`,
		userID, string(models.MediaAssetStatusReady), limit,
	)
	if err != nil {
		return nil, fmt.Errorf("list media assets: %w", err)
	}
	defer rows.Close()
	var result []models.MediaAsset
	for rows.Next() {
		asset, scanErr := scanMediaAsset(rows)
		if scanErr != nil {
			return nil, fmt.Errorf("scan media asset: %w", scanErr)
		}
		result = append(result, *asset)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate media assets: %w", err)
	}
	return result, nil
}

// ListVisibleInWorkspace returns the ready, non-expired media assets
// among mediaIDs that are visible to the workspace: the asset owner is
// the workspace owner OR a workspace member. Missing, foreign,
// not-ready, or expired assets are simply omitted — the same
// membership semantics CreateAsset enforces for thumbnail project
// assets, so a snapshot can never resolve a cross-workspace image.
// Backs the thumbnail media resolver endpoint.
func (r *MediaAssetRepository) ListVisibleInWorkspace(ctx context.Context, workspaceID int64, mediaIDs []string) ([]models.MediaAsset, error) {
	if workspaceID <= 0 {
		return nil, fmt.Errorf("list visible media assets: invalid workspace id %d", workspaceID)
	}
	if len(mediaIDs) == 0 {
		return nil, nil
	}
	rows, err := r.db.QueryContext(ctx,
		`SELECT `+mediaAssetColumns+`
		   FROM media_assets ma
		  WHERE ma.id = ANY($2::uuid[])
		    AND ma.status = $3
		    AND ma.expires_at > NOW()
		    AND EXISTS (
			    SELECT 1 FROM workspaces w
			     WHERE w.id = $1 AND (
				     w.owner_id = ma.user_id OR EXISTS (
					     SELECT 1 FROM workspace_members wm
					      WHERE wm.workspace_id = w.id AND wm.user_id = ma.user_id
				     )
			     )
		    )
		  ORDER BY ma.created_at DESC, ma.id`,
		workspaceID, pq.Array(mediaIDs), string(models.MediaAssetStatusReady))
	if err != nil {
		return nil, fmt.Errorf("list visible media assets: %w", err)
	}
	defer rows.Close()
	var result []models.MediaAsset
	for rows.Next() {
		asset, scanErr := scanMediaAsset(rows)
		if scanErr != nil {
			return nil, fmt.Errorf("scan visible media asset: %w", scanErr)
		}
		result = append(result, *asset)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate visible media assets: %w", err)
	}
	return result, nil
}

// SaveProbe persists the ffprobe-derived metadata for an asset
// (migration 092). Best-effort by design: the worker calls it after
// the probe succeeds and ignores errors (a probe failure must never
// fail an ingest job).
func (r *MediaAssetRepository) SaveProbe(id string, probe *models.MediaProbe) error {
	if probe == nil {
		return nil
	}
	_, err := r.db.Exec(
		`UPDATE media_assets
		    SET duration_seconds = $1, width = $2, height = $3, fps = $4,
		        has_audio = $5, video_codec = $6, audio_codec = $7,
		        probed_at = $8, updated_at = $8
		  WHERE id = $9`,
		probe.DurationSeconds, probe.Width, probe.Height, probe.FPS,
		probe.HasAudio, probe.VideoCodec, probe.AudioCodec, probe.ProbedAt, id,
	)
	if err != nil {
		return fmt.Errorf("save media probe: %w", err)
	}
	return nil
}

// FindForPost resolves a media asset only when it belongs to the post's
// workspace. The caller may provide the canonical asset id and/or the
// persisted bucket/object key mirror; when mirrors are present they must
// agree with the row, preventing stale or hand-edited post fields from
// selecting a different object. Membership is used rather than a user id
// on Post because posts are workspace-owned and may be published by any
// workspace member.
func (r *MediaAssetRepository) FindForPost(ctx context.Context, workspaceID int64, assetID, bucket, key string) (*models.MediaAsset, error) {
	if workspaceID <= 0 {
		return nil, fmt.Errorf("find media asset for post: invalid workspace id %d", workspaceID)
	}
	asset, err := scanMediaAsset(r.db.QueryRowContext(ctx,
		`SELECT ma.id, ma.user_id, ma.upload_key, ma.bucket, ma.content_type, ma.size_bytes, ma.status,
		        COALESCE(ma.sha256, ''), COALESCE(ma.error_message, ''), ma.expires_at, ma.created_at, ma.updated_at,
		        ma.duration_seconds, ma.width, ma.height, ma.fps, ma.has_audio,
		        ma.video_codec, ma.audio_codec, ma.probed_at
		 FROM media_assets ma
		 WHERE (
			($2 <> '' AND ma.id = NULLIF($2, '')::uuid)
			OR ($2 = '' AND $3 <> '' AND ma.upload_key = $3)
		 )
		 AND ($4 = '' OR ma.bucket = $4)
		 AND ($3 = '' OR ma.upload_key = $3)
		 AND EXISTS (
			SELECT 1 FROM workspaces w
			WHERE w.id = $1 AND (
				w.owner_id = ma.user_id OR EXISTS (
					SELECT 1 FROM workspace_members wm
					WHERE wm.workspace_id = w.id AND wm.user_id = ma.user_id
				)
			)
		 )`,
		workspaceID, assetID, key, bucket,
	))
	if err != nil {
		return nil, fmt.Errorf("failed to find owned media asset for post: %w", err)
	}
	return asset, nil
}

// FindByUploadKey is the legacy URL fallback, scoped to workspace
// membership so a legacy URL cannot become an IDOR publishing path.
func (r *MediaAssetRepository) FindByUploadKey(ctx context.Context, workspaceID int64, key string) (*models.MediaAsset, error) {
	if workspaceID <= 0 || key == "" {
		return nil, nil
	}
	asset, err := scanMediaAsset(r.db.QueryRowContext(ctx,
		`SELECT ma.id, ma.user_id, ma.upload_key, ma.bucket, ma.content_type, ma.size_bytes, ma.status,
		        COALESCE(ma.sha256, ''), COALESCE(ma.error_message, ''), ma.expires_at, ma.created_at, ma.updated_at,
		        ma.duration_seconds, ma.width, ma.height, ma.fps, ma.has_audio,
		        ma.video_codec, ma.audio_codec, ma.probed_at
		 FROM media_assets ma
		 WHERE ma.upload_key = $2
		 AND EXISTS (
			SELECT 1 FROM workspaces w
			WHERE w.id = $1 AND (
				w.owner_id = ma.user_id OR EXISTS (
					SELECT 1 FROM workspace_members wm
					WHERE wm.workspace_id = w.id AND wm.user_id = ma.user_id
				)
			)
		 ) LIMIT 1`,
		workspaceID, key,
	))
	if err != nil {
		return nil, fmt.Errorf("failed to find owned media asset by upload_key: %w", err)
	}
	return asset, nil
}

// MarkReady transitions an asset to `ready` after the /complete
// handler HEAD-verified the S3 object (or after the worker's
// streaming-compute path stamped a non-empty local SHA via the
// artifactVerifyReader). Task 6/10 contract:
//   - sha256 MUST be a 64-char lowercase hex string. Empty string is
//     REJECTED at the repo level via ErrMediaAssetSHARequired —
//     defence-in-depth on top of migration 056's NOT NULL constraint
//     (which only blocks SQL NULL, not the empty-string legacy
//     sentinel).
//   - sizeBytes + contentType are the server-measured values from
//     the upstream verification path (HEAD on the /complete handler;
//     streaming-tee-then-upload on the worker + drive import paths).
//     Both are required for the schema invariant, the /complete
//     handler must assert equality with the presign-declared values
//     BEFORE invoking MarkReady, and the worker streaming verify
//     must assert equality with the ArtifactVerificationPolicy
//     BEFORE invoking MarkReady. MarkReady itself does NOT
//     re-verify (the value was already verified at the call site;
//     re-verifying here would be redundant + would double the bytes
//     read on large uploads).
func (r *MediaAssetRepository) MarkReady(id, sha256 string, sizeBytes int64, contentType string) error {
	// Task 6/10 — runtime guard against the legacy empty-SHA
	// sentinel. Cheap O(1) reject in the hot path; the same value
	// would have been silently preserved by the prior
	// COALESCE(NULLIF($2, ''), sha256) SQL — a behaviour that
	// contradicts the user's spec ('MAI più stringa SHA vuota')
	// and the migration 056 NOT NULL intent. Today every production
	// caller wrapping the byte stream in an artifactVerifyReader
	// (Drive import, worker pull-path) passes
	// verifyReader.ActualSHA256Hex() which is always a non-empty
	// 64-hex; the /complete handler is the only path that could
	// historically have passed empty — handleCompleteMedia is
	// updated (Task 6/10) to reject empty SHA upfront with a 400
	// instead of letting the value reach MarkReady.
	if sha256 == "" {
		return fmt.Errorf("%w: media asset id=%s", ErrMediaAssetSHARequired, id)
	}
	now := time.Now()
	// SQL simplified: removed `COALESCE(NULLIF($2, ''), sha256)`
	// because the runtime guard above guarantees $2 is non-empty —
	// the COALESCE would be unreachable dead-code-by-condition.
	// Direct assignment makes the contract obvious in the diff
	// future readers will see (status='ready' implies a real SHA
	// was written, not a 'preserve legacy empty' gotcha).
	res, err := r.db.Exec(
		`UPDATE media_assets
		    SET status = $1, sha256 = $2,
		        size_bytes = $3, content_type = $4, error_message = '', updated_at = $5
		  WHERE id = $6`,
		string(models.MediaAssetStatusReady), sha256, sizeBytes, contentType, now, id,
	)
	if err != nil {
		return fmt.Errorf("failed to mark media asset ready: %w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("%w: media asset id=%s", ErrMediaAssetNotFound, id)
	}
	return nil
}

// MarkFailed transitions an asset to `failed` and records the reason.
// The /complete handler uses this when S3 HEAD returns 404, when the
// size/content-type don't match, or on any verification error.
func (r *MediaAssetRepository) MarkFailed(id, reason string) error {
	now := time.Now()
	res, err := r.db.Exec(
		`UPDATE media_assets
		    SET status = $1, error_message = $2, updated_at = $3
		  WHERE id = $4`,
		string(models.MediaAssetStatusFailed), reason, now, id,
	)
	if err != nil {
		return fmt.Errorf("failed to mark media asset failed: %w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("%w: media asset id=%s", ErrMediaAssetNotFound, id)
	}
	return nil
}

// MarkFailedWithReason is the diagnose-friendly variant of MarkFailed:
// the caller passes the underlying error (`cause`) so the helper can
// log it alongside the persist failure. The historical pattern was
// `_ = store.MarkFailed(id, err.Error())` — silent on second-failure,
// meaning an operator who noticed the original error rarely noticed
// that the failure-of-the-failure also failed. Centralising the
// "failure of the failure" log here means every "I tried to record
// failure" path emits one structured slog line.
//
// `cause` may be nil (e.g. when the caller shapes the reason itself);
// it's emitted only when non-nil. Returns the underlying persist
// error so callers that want to take further action (e.g. escalate
// via metric) can do so.
func (r *MediaAssetRepository) MarkFailedWithReason(id, reason string, cause error) error {
	err := r.MarkFailed(id, reason)
	if err != nil {
		slog.Error("media: failed to persist MarkFailed",
			"asset_id", id,
			"reason", reason,
			"cause", cause,
			"mark_err", err,
		)
	}
	return err
}

// MarkExpired is used by the cleanup pass that transitions any
// status=pending assets whose expires_at < NOW() to status=expired.
// Returns the number of rows affected.
func (r *MediaAssetRepository) MarkExpired(now time.Time) (int64, error) {
	res, err := r.db.Exec(
		`UPDATE media_assets
		    SET status = $1, updated_at = $2
		  WHERE status = $3 AND expires_at < $4`,
		string(models.MediaAssetStatusExpired), now,
		string(models.MediaAssetStatusPending), now,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to mark media assets expired: %w", err)
	}
	n, _ := res.RowsAffected()
	return n, nil
}

// DeleteEligibleAssets hard-deletes media_assets rows whose YouTube
// publish + post pipeline has fully run AND aged past retentionDays
// days (the operator-configured buffer; defaults to cfg.Worker
// .VideoRetentionBufferDays = 7 days).
//
// Single DELETE FROM ... USING round-trip across media_assets +
// upload_jobs + post_targets + youtube_target_publications. The
// canonical published-state semantics:
//   - youtube_target_publications.youtube_upload_status MUST equal
//     'youtube_uploaded' (the canonical uploaded-state string the
//     upload_worker stamps via MarkYouTubeUploaded).
//   - youtube_target_publications.published_at MUST be non-null
//     AND published_at + retentionDays < NOW() (the publish-window
//     has lapsed AND the operator-configured buffer has elapsed).
//   - NO post_targets row on the same post may be in
//     {'retrying','dlq'} -- operator-triage states where the asset
//     is still load-bearing for live debugging + audit.
//   - NO youtube_target_publications row on the same upload_job may
//     have publish_at > NOW() -- even if THIS row reached published,
//     a peer target may still have a future-scheduled publish so
//     the asset MUST stay alive until that lands.
//
// Returns the number of media_assets rows hard-deleted (int64 to
// match the cast­er pattern of pkg/repository.MarkExpired). (0,
// nil) is the normal "nothing eligible this tick" outcome. The
// caller (asset_cleanup_worker) decides whether the loop continues
// on error or backs off.
func (r *MediaAssetRepository) DeleteEligibleAssets(ctx context.Context, retentionDays int) (int64, error) {
	// Reviewer Sharp 1: cap retentionDays at 3650 (10 years) — Postgres
	// make_interval(days => $1) overflows into seconds-relative math
	// past ~2.5M days, and operators who mean "effectively disable"
	// should bump VideoRetentionBufferDays to a large value, not 0.
	// 3650 keeps operators safely above the overflow boundary while
	// still rejecting accidental `10000000`-style typos.
	if retentionDays <= 0 || retentionDays > 3650 {
		return 0, fmt.Errorf("media asset DeleteEligibleAssets: retentionDays must be between 1 and 3650 days (got %d)", retentionDays)
	}
	res, err := r.db.ExecContext(ctx,
		`DELETE FROM media_assets ma
		 USING upload_jobs uj, post_targets pt, youtube_target_publications ytp
			-- upload_jobs.asset_id is legacy TEXT while media_assets.id is UUID.
			-- Compare in the stable textual representation so cleanup works on
			-- existing installations without an invalid TEXT→UUID cast.
			WHERE ma.id::text = uj.asset_id
		   AND uj.post_id = pt.post_id
		   AND uj.id = ytp.upload_job_id
		   AND ytp.youtube_upload_status = 'youtube_uploaded'
		   AND ytp.published_at IS NOT NULL
		   AND ytp.published_at + make_interval(days => $1::int) < NOW()
		   AND NOT EXISTS (
			   SELECT 1 FROM post_targets pt2
			   WHERE pt2.post_id = uj.post_id
			     AND pt2.status IN ('retrying','dlq')
		   )
		   AND NOT EXISTS (
			   SELECT 1 FROM posts p
			   WHERE p.id = uj.post_id
			     AND p.publish_at IS NOT NULL
			     AND p.publish_at > NOW()
		   )
		   AND NOT EXISTS (
			   SELECT 1 FROM youtube_target_publications ytp2
			   WHERE ytp2.upload_job_id = uj.id
			     AND ytp2.publish_at IS NOT NULL
			     AND ytp2.publish_at > NOW()
		   )`, retentionDays)
	if err != nil {
		return 0, fmt.Errorf("media asset DeleteEligibleAssets: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("media asset DeleteEligibleAssets rows affected: %w", err)
	}
	return n, nil
}

// CleanupOnce is the AssetCleaner-interface-satisfying thin wrapper
// the worker wires against. Delegates to DeleteEligibleAssets with the
// configured retentionDays -- letting MediaAssetRepository satisfy
// both the repo internal contract AND the AssetCleanupWorker's
// narrower interface from a single concrete.
func (r *MediaAssetRepository) CleanupOnce(ctx context.Context, retentionDays int) (int64, error) {
	return r.DeleteEligibleAssets(ctx, retentionDays)
}
