-- =============================================================================
-- 054_external_destinations.sql — Velox integration (Phase 1 contract minimum)
-- =============================================================================
-- Why this migration exists:
--
-- The Velox <-> InstaEdit contract (docs/ARCHITECTURE.md + the user's
-- "Architettura corretta" memo) requires an OPAQUE destination pointer
-- that decouples the two systems:
--
--     Velox  → "externally I am producing a video for destination extdst_01J..."
--     InstaEdit → server-side resolves extdst_01J... → workspace, platform
--                 account, YouTube channel, OAuth token, publish defaults
--
-- Before this table, the only cross-system link was the public
-- `platform_accounts.channel_id` — Velox would have to know the
-- YouTube channel id, the workspace owner, and (worst) the OAuth
-- token lineage. The opaque-id pattern preserves a one-way data
-- flow: Velox never sees credentials, InstaEdit never sees Velox's
-- internal job/task IDs, and the resolution is centralised in one
-- row per (source_system, workspace, platform_account) triple.
--
-- Why a NEW table (not a column on platform_accounts):
--
--   1. There can be MANY external integrations per workspace over
--      time (Velox + future "S3 bucket drop" + future "Dropbox" +
--      ...). A flat column would need one row per integration
--      system × workspace × account, which is a join either way
--      but with a column we'd need many columns. A separate
--      table expresses "many possible external systems" cleanly
--      and naturally extends forward.
--   2. `default_metadata` is external-system-specific (passes
--      through to the publish_worker as PrivacyLevel/language).
--      platform_accounts has no place for per-source defaults.
--   3. `enabled` is per-binding (a Velox destination can be
--      disabled for a workspace without affecting the underlying
--      platform_account). Same pattern as migration 044
--      workspace_channels.
--
-- Opaque ID shape:
--
--   "extdst_01J...." — the "01J" prefix encodes an ULID
--   (Universally Unique Lexicographically Sortable Identifier)
--   with the "extdst_" discriminator so an operator scanning
--   logs can spot these IDs at a glance, distinct from
--   upload_job bigint ids, post bigint ids, or workspace
--   bigint ids. The handler enforces the prefix at write-time
--   (POST /api/v1/integrations/velox/destinations validates
--   and stamps the prefix before INSERT). The DB only stores
--   TEXT — it neither generates nor parses the prefix; the
--   application owns that contract (50_yyyymm service-layer
--   helper).
--
-- Idempotency:
--
--   Migration runner (internal/database/migrations.go::
--   RunMigrations) executes every .sql on every startup with
--   NO schema_migrations table — so every DDL MUST be
--   idempotent on its own. CREATE TABLE IF NOT EXISTS +
--   CREATE INDEX IF NOT EXISTS are the established patterns
--   (see migration 043, 044, 050).
--
-- Why NO canary-list addition in migrate_check.go:
--
--   The /ready endpoint's canary list (users, platform_accounts,
--   tokens, workspaces, posts, post_targets, media_assets,
--   webhook_deliveries, outbox_events) represents the
--   PUBLIC readiness surface. Internal integration tables
--   (workspace_channels, oauth_connections, idempotency_*,
--   import_batches) are deliberately excluded. external_destinations
--   belongs in the same "internal" tier — adding it to the
--   canary list would couple /ready to this migration's drift,
--   which contradicts the design goal "canaries = invariant
--   surface every Blocco since #1.1 has relied on".
-- =============================================================================

CREATE TABLE IF NOT EXISTS external_destinations (
    -- Opaque identifier generated by the application layer (ULID
    -- with the `extdst_` discriminator). TEXT (not UUID/BYTEA)
    -- keeps the prefix human-readable in logs and queries —
    -- matching the spec value `extdst_01JABC` verbatim.
    id                  TEXT        PRIMARY KEY,

    -- Discriminator for the upstream system owning this row. Today
    -- only "velox" is registered; future integrations
    -- ("dropbox", "s3_drop") extend the column without a
    -- migration because the row already exists. Indexed
    -- separately for "list all destinations for source X".
    source_system       TEXT        NOT NULL,

    -- Workspace that owns this destination. CASCADE on delete
    -- because every channel within a workspace belongs to it
    -- (matches 044_workspace_channels cascade policy; removes
    -- orphaned destinations when a workspace is purged).
    workspace_id        BIGINT      NOT NULL
        REFERENCES workspaces(id) ON DELETE CASCADE,

    -- Underlying channel / page / account. CASCADE on delete
    -- because the destination is meaningless without its
    -- underlying OAuth-protected resource (matches 044 again;
    -- a removed channel leaves no destination behind).
    platform_account_id BIGINT      NOT NULL
        REFERENCES platform_accounts(id) ON DELETE CASCADE,

    -- Operator toggle. A disabled destination MUST NOT be picked
    -- by Velox on /internal/v1/destinations/{id}/validate (return
    -- 4xx). The handler enforces this; the partial index below
    -- keeps the "list enabled destinations per workspace" query
    -- tight.
    enabled             BOOLEAN     NOT NULL DEFAULT TRUE,

    -- Per-tenant defaults stamped onto the publish_payload when
    -- this destination is the route. Shape matches the user's
    -- spec:
    --     {
    --         "privacy_status": "private" | "unlisted" | "public",
    --         "language":       ISO 639-1 (e.g. "it"),
    --         "timezone":       IANA tz (e.g. "Europe/Rome"),
    --         "tags":           ["tag1", ...]   (optional)
    --     }
    -- JSONB (not TEXT) so the worker can JSON_EXTRACT individual
    -- defaults without re-parsing. Empty default = worker asks
    -- the per-post payload for the missing field.
    default_metadata    JSONB       NOT NULL DEFAULT '{}'::jsonb,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- One destination per (upstream × workspace × channel) tuple.
    -- Prevents accidental double-linking (e.g. an operator
    -- double-clicking the admin Connetti button). The UNIQUE
    -- index is the natural conflict surface; the INSERT path
    -- handles ON CONFLICT cleanly.
    UNIQUE (source_system, workspace_id, platform_account_id)
);

-- Partial index for "list enabled destinations belonging to this
-- workspace" — the admin dashboard's main lookup path. The
-- WHERE clause excludes the (rare) disabled set so the index
-- stays small even if operators disable a third of the fleet.
CREATE INDEX IF NOT EXISTS idx_external_destinations_workspace_enabled
    ON external_destinations (workspace_id)
    WHERE enabled = TRUE;

-- By-source roster index. Useful for "/admin/health: list every
-- destination for source X across the fleet" — needed by
-- jack-link admin operations and by the "Token rotation" alert
-- that groups oauth_connections by upstream subject.
CREATE INDEX IF NOT EXISTS idx_external_destinations_source_system
    ON external_destinations (source_system, workspace_id);

COMMENT ON TABLE  external_destinations IS
    'Velox → InstaEdit opaque destination pointer. Resolves extdst_01J... → (workspace, platform_account, channel, token) server-side; the upstream system NEVER receives credentials. Future extensions (Dropbox/S3) add rows with new source_system values.';
COMMENT ON COLUMN external_destinations.id IS
    'Opaque ULID with `extdst_` prefix generated application-side. NOT DB-generated. Distinct from workspace/platform_account/internal IDs for log scannability.';
COMMENT ON COLUMN external_destinations.source_system IS
    'Upstream discriminator. Today: "velox". Future: "dropbox", "s3_drop", etc. No FK — extensions are application-registered, not DB-constrained.';
COMMENT ON COLUMN external_destinations.default_metadata IS
    'JSONB: per-tenant publish defaults (privacy_status, language, timezone, tags). Empty default means worker asks per-post payload for the missing field. JSONB so worker can JSON_EXTRACT without re-parse.';
COMMENT ON COLUMN external_destinations.enabled IS
    'Operator toggle. Disabled destinations return 4xx on /validate and are skipped by Velox. Enforced handler-side; partial index above excludes disabled rows from the main lookup.';
