package services

import (
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

// ---------------------------------------------------------------------------
// ProviderError basics
// ---------------------------------------------------------------------------

// TestProviderError_ImplementsError pins the error interface
// contract. The compile-time check on `var _ error = (*ProviderError)(nil)`
// would catch a regression; this test also documents it.
func TestProviderError_ImplementsError(t *testing.T) {
	var _ error = (*ProviderError)(nil)
	e := &ProviderError{Platform: "tiktok", Code: ErrorCodeRateLimited}
	if e.Error() == "" {
		t.Fatal("Error() returned empty string")
	}
}

// TestProviderError_ErrorFormat verifies the canonical Error()
// format: "{platform}: {code} ({safe_message})". A regression that
// changes the format would break log scrapers and the API layer's
// user-facing error messages.
func TestProviderError_ErrorFormat(t *testing.T) {
	e := &ProviderError{
		Platform:    "tiktok",
		Code:        ErrorCodeRateLimited,
		SafeMessage: "tiktok operation failed (status 429): rate limited",
	}
	want := "tiktok: rate_limited (tiktok operation failed (status 429): rate limited)"
	if got := e.Error(); got != want {
		t.Errorf("Error() = %q, want %q", got, want)
	}
}

// TestProviderError_ErrorFormat_NoSafeMessage: when SafeMessage
// is empty (e.g. zero-value struct), the message is the shorter
// "{platform}: {code}" form so we never emit an empty parens.
func TestProviderError_ErrorFormat_NoSafeMessage(t *testing.T) {
	e := &ProviderError{Platform: "tiktok", Code: ErrorCodeRateLimited}
	want := "tiktok: rate_limited"
	if got := e.Error(); got != want {
		t.Errorf("Error() = %q, want %q", got, want)
	}
}

// TestProviderError_UnwrapsCause verifies the error chain:
// errors.Is(pe, cause) must return true so callers can detect
// transport-layer causes (context.Canceled, io.EOF, etc.) through
// the ProviderError wrapping.
func TestProviderError_UnwrapsCause(t *testing.T) {
	cause := errors.New("underlying network timeout")
	pe := &ProviderError{Platform: "tiktok", Code: ErrorCodeProviderUnavailable, Cause: cause}
	if !errors.Is(pe, cause) {
		t.Errorf("errors.Is should find Cause through the wrap; err = %v", pe)
	}
}

// TestProviderError_SafeMessageDoesNotLeakBody is the CRITICAL
// security test. The raw provider body may contain user PII,
// internal tokens, or other sensitive data. The SafeMessage must
// NEVER contain any of the body substring. A regression here would
// be a privacy incident. Also covers the body → Cause autopreserve
// branch (when caller passes nil cause).
func TestProviderError_SafeMessageDoesNotLeakBody(t *testing.T) {
	body := `{"error": "secret_pii_account_12345: leaked internal token abcdef"}`
	err := NewProviderError("twitter", 400, body, http.Header{}, nil)
	// 1. Error() must not contain any of the body substring.
	if strings.Contains(err.Error(), "secret_pii_account_12345") {
		t.Fatalf("Error() leaked body substring: %s", err.Error())
	}
	if strings.Contains(err.Error(), "leaked internal token") {
		t.Fatalf("Error() leaked body substring: %s", err.Error())
	}
	if strings.Contains(err.SafeMessage, "secret_pii_account_12345") {
		t.Fatalf("SafeMessage leaked body substring: %s", err.SafeMessage)
	}
	// 2. Cause must contain the body (body autopreserve when caller
	// passes nil). The truncateForLog helper caps at 256 chars so
	// huge bodies don't bloat the cause chain.
	if err.Cause == nil {
		t.Fatal("Cause should preserve the raw error for debug; got nil")
	}
	if !strings.Contains(err.Cause.Error(), "secret_pii_account_12345") {
		t.Errorf("Cause should contain body substring for debug logs; got %q", err.Cause.Error())
	}
}

// TestProviderError_CallerCausePreserved covers the OTHER arm of
// the cause-preservation branch: when the caller passes a non-nil
// cause, the caller's cause must be preserved VERBATIM and the
// body is NOT wrapped into it. Otherwise a caller attaching their
// own rich context (e.g. "twitter 2/tweets: ...") would have it
// silently overridden by an autogenerated "provider body (truncated): ...".
func TestProviderError_CallerCausePreserved(t *testing.T) {
	body := `{"error": "ignore_me_for_cause"}`
	callerCause := errors.New("twitter 2/tweets ctx: caller-attach")
	err := NewProviderError("twitter", 400, body, http.Header{}, callerCause)
	if err.Cause != callerCause {
		t.Fatalf("Cause: want caller-supplied %v, got %v", callerCause, err.Cause)
	}
	if strings.Contains(err.Cause.Error(), "ignore_me_for_cause") {
		t.Errorf("Cause should NOT contain autogenerated body wrap; got %q", err.Cause.Error())
	}
}

// TestProviderError_DefaultsFilled verifies the constructor fills
// all expected fields: Code, Platform, SafeMessage, StatusCode, and
// (where applicable) Retryable / RetryAfter. A regression that
// drops a field would surface as a missing key in the API response.
func TestProviderError_DefaultsFilled(t *testing.T) {
	h := http.Header{}
	h.Set("Retry-After", "90")
	err := NewProviderError("linkedin", 429, `{"serviceErrorCode":429}`, h, nil)
	if err.Code != ErrorCodeRateLimited {
		t.Errorf("Code: want %q, got %q", ErrorCodeRateLimited, err.Code)
	}
	if !err.Retryable {
		t.Errorf("Retryable: want true for rate_limited, got false")
	}
	if err.RetryAfter != 90*time.Second {
		t.Errorf("RetryAfter: want 90s, got %v", err.RetryAfter)
	}
	if err.Platform != "linkedin" {
		t.Errorf("Platform: want %q, got %q", "linkedin", err.Platform)
	}
	if err.StatusCode != 429 {
		t.Errorf("StatusCode: want 429, got %d", err.StatusCode)
	}
	if err.ProviderCode != "429" {
		t.Errorf("ProviderCode: want %q, got %q", "429", err.ProviderCode)
	}
	if err.SafeMessage == "" {
		t.Errorf("SafeMessage: want non-empty, got empty")
	}
}

// TestProviderError_NilSafe verifies that calling Error() on a
// nil *ProviderError doesn't panic. Defensive — callers sometimes
// do `if pe := ...; pe != nil` and a panic here would be a crash.
func TestProviderError_NilSafe(t *testing.T) {
	var pe *ProviderError
	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("Error() panicked on nil receiver: %v", r)
		}
	}()
	got := pe.Error()
	if got != "<nil ProviderError>" {
		t.Errorf("Error() on nil: want %q, got %q", "<nil ProviderError>", got)
	}
}

// ---------------------------------------------------------------------------
// IsProviderError / IsRateLimitError
// ---------------------------------------------------------------------------

// TestIsProviderError_DetectsTyped: a direct *ProviderError is
// detected by IsProviderError.
func TestIsProviderError_DetectsTyped(t *testing.T) {
	err := &ProviderError{Platform: "tiktok", Code: ErrorCodeRateLimited}
	pe, ok := IsProviderError(err)
	if !ok {
		t.Fatal("IsProviderError should return true for *ProviderError")
	}
	if pe.Code != ErrorCodeRateLimited {
		t.Errorf("returned *ProviderError: want Code=%q, got %q", ErrorCodeRateLimited, pe.Code)
	}
}

// TestIsProviderError_DetectsWrapped: an *ProviderError wrapped in
// fmt.Errorf("...: %w", pe) is still detected.
func TestIsProviderError_DetectsWrapped(t *testing.T) {
	pe := &ProviderError{Platform: "tiktok", Code: ErrorCodeRateLimited}
	wrapped := fmt.Errorf("context: %w", pe)
	got, ok := IsProviderError(wrapped)
	if !ok {
		t.Fatal("IsProviderError should detect *ProviderError through fmt.Errorf wrap")
	}
	if got.Code != ErrorCodeRateLimited {
		t.Errorf("Code through wrap: want %q, got %q", ErrorCodeRateLimited, got.Code)
	}
}

// TestIsProviderError_NonProviderError: a plain error or unrelated
// type is NOT detected.
func TestIsProviderError_NonProviderError(t *testing.T) {
	plain := errors.New("plain error")
	if _, ok := IsProviderError(plain); ok {
		t.Fatal("IsProviderError should return false for plain errors.New")
	}
	// Also nil.
	if _, ok := IsProviderError(nil); ok {
		t.Fatal("IsProviderError should return false for nil")
	}
}

// TestIsRateLimitError_DetectsLegacy: backward compat with
// SPRINT 5.2 — the existing *RateLimitError type is still detected.
func TestIsRateLimitError_DetectsLegacy(t *testing.T) {
	rle := &RateLimitError{RetryAfter: 60 * time.Second}
	if !IsRateLimitError(rle) {
		t.Fatal("IsRateLimitError should detect legacy *RateLimitError")
	}
	// Also wrapped.
	wrapped := fmt.Errorf("publish target failed: %w", rle)
	if !IsRateLimitError(wrapped) {
		t.Fatal("IsRateLimitError should detect wrapped *RateLimitError")
	}
}

// TestIsRateLimitError_DetectsNewProviderError: the new canonical
// *ProviderError{Code: rate_limited} is also detected — this is
// the bridge from SPRINT 5.2 to SPRINT 5.1.
func TestIsRateLimitError_DetectsNewProviderError(t *testing.T) {
	pe := &ProviderError{Platform: "tiktok", Code: ErrorCodeRateLimited, RetryAfter: 30 * time.Second}
	if !IsRateLimitError(pe) {
		t.Fatal("IsRateLimitError should detect *ProviderError{Code: rate_limited}")
	}
	// Wrapped.
	wrapped := fmt.Errorf("publish failed: %w", pe)
	if !IsRateLimitError(wrapped) {
		t.Fatal("IsRateLimitError should detect wrapped *ProviderError{Code: rate_limited}")
	}
}

// TestIsRateLimitError_NonRateLimit: a ProviderError with a
// different code is NOT detected.
func TestIsRateLimitError_NonRateLimit(t *testing.T) {
	pe := &ProviderError{Platform: "tiktok", Code: ErrorCodeAuthenticationError}
	if IsRateLimitError(pe) {
		t.Fatal("IsRateLimitError should return false for non-rate_limited ProviderError")
	}
}

// ---------------------------------------------------------------------------
// MapHTTPStatus
// ---------------------------------------------------------------------------

// TestMapHTTPStatus covers the canonical HTTP status → taxonomy
// code mapping for 4xx and 5xx. The function is documented as
// not-for-2xx/3xx; those cases are NOT in the table (a regression
// returning "" for 200 would silently slip through if they were,
// because there's no positive assertion for them). The taxonomy
// is the contract that the worker / API layer act on; a regression
// here changes the retry behavior of every provider.
func TestMapHTTPStatus(t *testing.T) {
	cases := []struct {
		status int
		want   ProviderErrorCode
	}{
		{http.StatusBadRequest, ErrorCodeValidationError},
		{401, ErrorCodeAuthenticationError},
		{http.StatusPaymentRequired, ErrorCodeQuotaExceeded},
		{http.StatusForbidden, ErrorCodePermissionMissing},
		{http.StatusNotFound, ErrorCodeContentRejected},
		{http.StatusGone, ErrorCodeContentRejected},
		{http.StatusTooManyRequests, ErrorCodeRateLimited},
		{418, ErrorCodeValidationError},    // 4xx catch-all
		{451, ErrorCodeValidationError},    // 4xx catch-all
		{http.StatusInternalServerError, ErrorCodeProviderUnavailable},
		{http.StatusBadGateway, ErrorCodeProviderUnavailable},
		{http.StatusServiceUnavailable, ErrorCodeProviderUnavailable},
		{599, ErrorCodeProviderUnavailable},
		{0, ErrorCodeInternalError}, // 0 = not-applicable defensive default
	}
	for _, c := range cases {
		got := MapHTTPStatus(c.status)
		if got != c.want {
			t.Errorf("MapHTTPStatus(%d) = %q, want %q", c.status, got, c.want)
		}
	}
}

// ---------------------------------------------------------------------------
// ParseThrottleHeaders
// ---------------------------------------------------------------------------

// TestParseThrottleHeaders covers the canonical header order +
// per-platform quirks. The worker relies on this for the
// retry-after the rate-limit handler stamps onto post_targets.
func TestParseThrottleHeaders(t *testing.T) {
	cases := []struct {
		name    string
		header  http.Header
		want    time.Duration
	}{
		{
			name:   "Retry-After delta-seconds (RFC 7231)",
			header: http.Header{"Retry-After": {"120"}},
			want:   120 * time.Second,
		},
		{
			name:   "X-RateLimit-Reset epoch (GitHub/Stripe/YouTube)",
			header: http.Header{"X-Ratelimit-Reset": {fmt.Sprintf("%d", time.Now().Add(90*time.Second).Unix())}},
			want:   90 * time.Second, // ±2s due to test wall clock
		},
		{
			name:   "X-Rate-Limit-Reset alt spelling",
			header: http.Header{"X-Rate-Limit-Reset": {"60"}},
			want:   60 * time.Second,
		},
		{
			name:   "x-rate-limit-reset lowercase (Twitter v2)",
			header: http.Header{"X-Rate-Limit-Reset": {"45"}}, // Canonical form (Go canonicalizes header keys)
			want:   45 * time.Second,
		},
		{
			name:   "missing all throttle headers",
			header: http.Header{},
			want:   0,
		},
		{
			name:   "Retry-After unparseable",
			header: http.Header{"Retry-After": {"not-a-number"}},
			want:   0,
		},
		{
			name: "prefers Retry-After over X-RateLimit-Reset (canonical first)",
			header: http.Header{
				"Retry-After":       {"30"},
				"X-Ratelimit-Reset": {"999999999"}, // 11+ years in the future
			},
			want: 30 * time.Second,
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := ParseThrottleHeaders(c.header)
			if c.want == 0 {
				if got != 0 {
					t.Errorf("want 0, got %v", got)
				}
				return
			}
			// Allow ±2s tolerance for epoch-based tests (test wall
			// clock vs the value computed at test setup).
			diff := got - c.want
			if diff < 0 {
				diff = -diff
			}
			if diff > 2*time.Second {
				t.Errorf("want ~%v, got %v (diff %v)", c.want, got, diff)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Per-platform body parsers
// ---------------------------------------------------------------------------

// TestParseMetaErrorBody: the Meta Graph API error shape
// {error: {code, error_subcode}} maps to "code:subcode" for the
// ProviderCode. x-fb-trace-id becomes RequestID. Also covers the
// isMetaRateLimit fourth return value.
func TestParseMetaErrorBody(t *testing.T) {
	h := http.Header{}
	h.Set("x-fb-trace-id", "AbCdEfGhIjK")
	body := `{"error":{"code":190,"error_subcode":4,"message":"Invalid OAuth access token"}}`
	code, reqID, _, rl := parseMetaErrorBody(body, h)
	if code != "190:4" {
		t.Errorf("ProviderCode: want %q, got %q", "190:4", code)
	}
	if reqID != "AbCdEfGhIjK" {
		t.Errorf("RequestID: want %q, got %q", "AbCdEfGhIjK", reqID)
	}
	if !rl {
		t.Errorf("isMetaRateLimit: want true (error_subcode 4), got false")
	}
}

// TestParseMetaErrorBody_NoSubcode: when error_subcode is absent,
// the ProviderCode is just the top-level code (no trailing colon)
// and isMetaRateLimit is false.
func TestParseMetaErrorBody_NoSubcode(t *testing.T) {
	body := `{"error":{"code":100,"message":"Invalid parameter"}}`
	code, _, _, rl := parseMetaErrorBody(body, http.Header{})
	if code != "100" {
		t.Errorf("ProviderCode: want %q, got %q", "100", code)
	}
	if rl {
		t.Errorf("isMetaRateLimit: want false (no subcode), got true")
	}
}

// TestParseMetaErrorBody_UnparseableBody: a non-JSON body returns
// empty ProviderCode (no panic) and isMetaRateLimit=false. The
// caller still has a working ProviderError, just with less detail.
func TestParseMetaErrorBody_UnparseableBody(t *testing.T) {
	code, reqID, _, rl := parseMetaErrorBody("not json", http.Header{})
	if code != "0" {
		t.Errorf("ProviderCode: want %q, got %q", "0", code)
	}
	if reqID != "" {
		t.Errorf("RequestID: want empty, got %q", reqID)
	}
	if rl {
		t.Errorf("isMetaRateLimit: want false (no JSON), got true")
	}
}

// TestParseYouTubeErrorBody: error.errors[0].reason becomes the
// ProviderCode (e.g. "quotaExceeded").
func TestParseYouTubeErrorBody(t *testing.T) {
	h := http.Header{}
	h.Set("x-request-id", "youtube-req-123")
	body := `{"error":{"code":403,"message":"Quota exceeded","errors":[{"reason":"quotaExceeded","domain":"youtube.quota"}]}}`
	code, reqID, _ := parseYouTubeErrorBody(body, h)
	if code != "quotaExceeded" {
		t.Errorf("ProviderCode: want %q, got %q", "quotaExceeded", code)
	}
	if reqID != "youtube-req-123" {
		t.Errorf("RequestID: want %q, got %q", "youtube-req-123", reqID)
	}
}

// TestParseYouTubeErrorBody_ProcessingFailed: the YouTube
// processingFailed reason maps to media_processing_failed upstream
// (the worker interprets ProviderCode via the code, not the body).
func TestParseYouTubeErrorBody_ProcessingFailed(t *testing.T) {
	body := `{"error":{"errors":[{"reason":"processingFailed"}]}}`
	code, _, _ := parseYouTubeErrorBody(body, http.Header{})
	if code != "processingFailed" {
		t.Errorf("ProviderCode: want %q, got %q", "processingFailed", code)
	}
}

// TestParseTwitterErrorBody: errors[0].code is the numeric Twitter
// v2 code (89 = invalid token, 32 = not authenticated, 88 = rate limit).
func TestParseTwitterErrorBody(t *testing.T) {
	h := http.Header{}
	h.Set("x-request-id", "twitter-req-abc")
	body := `{"errors":[{"code":89,"message":"Invalid or expired token."}],"title":"Unauthorized","type":"about:blank"}`
	code, reqID, _ := parseTwitterErrorBody(body, h)
	if code != "89" {
		t.Errorf("ProviderCode: want %q, got %q", "89", code)
	}
	if reqID != "twitter-req-abc" {
		t.Errorf("RequestID: want %q, got %q", "twitter-req-abc", reqID)
	}
}

// TestParseTwitterErrorBody_RateLimit: Twitter's rate-limit code
// is 88 (API v1.1) or 429 (v2). Either way, the NewProviderError
// constructor will map 429 → rate_limited via the status code.
func TestParseTwitterErrorBody_RateLimit(t *testing.T) {
	body := `{"errors":[{"code":88,"message":"Rate limit exceeded"}]}`
	code, _, _ := parseTwitterErrorBody(body, http.Header{})
	if code != "88" {
		t.Errorf("ProviderCode: want %q, got %q", "88", code)
	}
}

// TestParseLinkedInErrorBody: serviceErrorCode is numeric
// (401 = invalid token, 403 = insufficient scope, 429 = throttle).
func TestParseLinkedInErrorBody(t *testing.T) {
	h := http.Header{}
	h.Set("x-li-id", "linkedin-req-xyz")
	body := `{"serviceErrorCode":401,"message":"Invalid access token","status":401}`
	code, reqID, _ := parseLinkedInErrorBody(body, h)
	if code != "401" {
		t.Errorf("ProviderCode: want %q, got %q", "401", code)
	}
	if reqID != "linkedin-req-xyz" {
		t.Errorf("RequestID: want %q, got %q", "linkedin-req-xyz", reqID)
	}
}

// TestParseLinkedInErrorBody_Throttle: LinkedIn's throttle code
// is 429. The status-only mapping also catches it.
func TestParseLinkedInErrorBody_Throttle(t *testing.T) {
	body := `{"serviceErrorCode":429,"message":"Throttle limit reached","status":429}`
	code, _, _ := parseLinkedInErrorBody(body, http.Header{})
	if code != "429" {
		t.Errorf("ProviderCode: want %q, got %q", "429", code)
	}
}

// TestParseTikTokErrorBody: error.code is a string
// (e.g. "spam_risk", "rate_limit_exceeded"). x-tt-logid is the request id.
func TestParseTikTokErrorBody(t *testing.T) {
	h := http.Header{}
	h.Set("x-tt-logid", "tiktok-log-789")
	body := `{"error":{"code":"spam_risk_too_many_posts","message":"too many posts today","log_id":"tiktok-log-789"}}`
	code, reqID, _ := parseTikTokErrorBody(body, h)
	if code != "spam_risk_too_many_posts" {
		t.Errorf("ProviderCode: want %q, got %q", "spam_risk_too_many_posts", code)
	}
	if reqID != "tiktok-log-789" {
		t.Errorf("RequestID: want %q, got %q", "tiktok-log-789", reqID)
	}
}

// TestParseTikTokErrorBody_HeaderFallback: when the body has no
// error.code but the x-tt-error-code header is set, fall back to
// the header.
func TestParseTikTokErrorBody_HeaderFallback(t *testing.T) {
	h := http.Header{}
	h.Set("x-tt-error-code", "invalid_params")
	code, _, _ := parseTikTokErrorBody(`{"error":{"message":"bad input"}}`, h)
	if code != "invalid_params" {
		t.Errorf("ProviderCode: want %q, got %q", "invalid_params", code)
	}
}

// ---------------------------------------------------------------------------
// NewProviderError adapter (httptest + canonical scenarios)
// ---------------------------------------------------------------------------

// TestNewProviderError_Adapter_401 covers the canonical "external
// 401 → authentication_error" mapping. The user spec required
// "at least 2-3 external error forms → taxonomy" — this is one
// of the three.
func TestNewProviderError_Adapter_401(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"error":"invalid_token"}`))
	}))
	defer ts.Close()
	resp, err := http.Get(ts.URL)
	if err != nil {
		t.Fatalf("setup: %v", err)
	}
	defer resp.Body.Close()
	bodyBuf := make([]byte, 256)
	n, _ := resp.Body.Read(bodyBuf)

	pe := NewProviderError("tiktok", resp.StatusCode, string(bodyBuf[:n]), resp.Header, nil)
	if pe.Code != ErrorCodeAuthenticationError {
		t.Errorf("Code: want %q, got %q", ErrorCodeAuthenticationError, pe.Code)
	}
	if pe.StatusCode != http.StatusUnauthorized {
		t.Errorf("StatusCode: want %d, got %d", http.StatusUnauthorized, pe.StatusCode)
	}
	// SafeMessage must not contain the body substring.
	if strings.Contains(pe.SafeMessage, "invalid_token") {
		t.Errorf("SafeMessage leaked body: %q", pe.SafeMessage)
	}
	// 401 is NOT retryable (auth required).
	if pe.Retryable {
		t.Errorf("401 should NOT be retryable; got Retryable=true")
	}
}

// TestNewProviderError_Adapter_429 covers "external 429 → rate_limited
// + Retry-After". The third of the three required external scenarios.
func TestNewProviderError_Adapter_429(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Retry-After", "60")
		w.WriteHeader(http.StatusTooManyRequests)
		w.Write([]byte(`{"error":"rate_limited"}`))
	}))
	defer ts.Close()
	resp, err := http.Get(ts.URL)
	if err != nil {
		t.Fatalf("setup: %v", err)
	}
	defer resp.Body.Close()
	bodyBuf := make([]byte, 256)
	n, _ := resp.Body.Read(bodyBuf)

	pe := NewProviderError("twitter", resp.StatusCode, string(bodyBuf[:n]), resp.Header, nil)
	if pe.Code != ErrorCodeRateLimited {
		t.Errorf("Code: want %q, got %q", ErrorCodeRateLimited, pe.Code)
	}
	if pe.RetryAfter != 60*time.Second {
		t.Errorf("RetryAfter: want 60s, got %v", pe.RetryAfter)
	}
	if !pe.Retryable {
		t.Errorf("429 should be retryable; got Retryable=false")
	}
	if strings.Contains(pe.SafeMessage, "rate_limited") == false {
		// SafeMessage contains the category "rate limited" (with
		// space) — verify the underscore was replaced.
		if !strings.Contains(pe.SafeMessage, "rate limited") {
			t.Errorf("SafeMessage should contain 'rate limited' category; got %q", pe.SafeMessage)
		}
	}
}

// TestNewProviderError_Adapter_503 covers "external 5xx →
// provider_unavailable + retryable". The second of the three
// required external scenarios.
func TestNewProviderError_Adapter_503(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusServiceUnavailable)
		w.Write([]byte(`<html>nginx is down</html>`))
	}))
	defer ts.Close()
	resp, err := http.Get(ts.URL)
	if err != nil {
		t.Fatalf("setup: %v", err)
	}
	defer resp.Body.Close()
	bodyBuf := make([]byte, 1024)
	n, _ := resp.Body.Read(bodyBuf)

	pe := NewProviderError("youtube", resp.StatusCode, string(bodyBuf[:n]), resp.Header, nil)
	if pe.Code != ErrorCodeProviderUnavailable {
		t.Errorf("Code: want %q, got %q", ErrorCodeProviderUnavailable, pe.Code)
	}
	if !pe.Retryable {
		t.Errorf("503 should be retryable; got Retryable=false")
	}
	if strings.Contains(pe.SafeMessage, "nginx") {
		t.Errorf("SafeMessage leaked body: %q", pe.SafeMessage)
	}
}

// TestNewProviderError_Meta_RateLimit_Subcode covers the Meta-
// specific override: error_subcode 4 with a 400 status maps to
// rate_limited, not validation_error. This is the canonical
// "Meta returns 400 for app-level rate limits" case.
func TestNewProviderError_Meta_RateLimit_Subcode(t *testing.T) {
	body := `{"error":{"code":4,"error_subcode":4,"message":"Application request limit reached","type":"OAuthException"}}`
	pe := NewProviderError("instagram", http.StatusBadRequest, body, http.Header{}, nil)
	if pe.Code != ErrorCodeRateLimited {
		t.Errorf("Code: want %q (Meta subcode 4 = rate-limited), got %q", ErrorCodeRateLimited, pe.Code)
	}
	if !pe.Retryable {
		t.Errorf("Meta rate-limit should be retryable; got Retryable=false")
	}
	if pe.ProviderCode != "4:4" {
		t.Errorf("ProviderCode: want %q, got %q", "4:4", pe.ProviderCode)
	}
}

// TestNewProviderError_NewRateLimitErrorConstructor: the
// convenience constructor returns a fully-populated ProviderError
// without needing an HTTP response. The status/SafeMessage/
// ProviderCode/RequestID defaults are pinned: callers downstream
// (the API layer that builds a JSON error response) depend on
// these NOT being zero values.
func TestNewProviderError_NewRateLimitErrorConstructor(t *testing.T) {
	pe := NewRateLimitError("linkedin", 90*time.Second)
	if pe.Code != ErrorCodeRateLimited {
		t.Errorf("Code: want %q, got %q", ErrorCodeRateLimited, pe.Code)
	}
	if pe.RetryAfter != 90*time.Second {
		t.Errorf("RetryAfter: want 90s, got %v", pe.RetryAfter)
	}
	if !pe.Retryable {
		t.Errorf("rate_limited should be retryable; got Retryable=false")
	}
	if pe.StatusCode != http.StatusTooManyRequests {
		t.Errorf("StatusCode: want 429 (the constructor must pin this), got %d", pe.StatusCode)
	}
	if pe.Platform != "linkedin" {
		t.Errorf("Platform: want %q, got %q", "linkedin", pe.Platform)
	}
	if pe.SafeMessage == "" {
		t.Errorf("SafeMessage: want non-empty, got empty")
	}
	if !strings.Contains(pe.SafeMessage, "linkedin") {
		t.Errorf("SafeMessage: should contain platform name %q; got %q", "linkedin", pe.SafeMessage)
	}
	if !strings.Contains(pe.SafeMessage, "rate limited") {
		t.Errorf("SafeMessage: should contain category 'rate limited'; got %q", pe.SafeMessage)
	}
	if pe.ProviderCode != "" {
		t.Errorf("ProviderCode: want empty (no upstream body parsed), got %q", pe.ProviderCode)
	}
	if pe.RequestID != "" {
		t.Errorf("RequestID: want empty (no upstream headers parsed), got %q", pe.RequestID)
	}
	if pe.Cause != nil {
		t.Errorf("Cause: want nil (constructor never sets it), got %v", pe.Cause)
	}
}

// TestAllProviderErrorCodes_ReturnsAll10 pins the taxonomy
// surface: any addition / removal is a breaking change for
// clients that pin the code set.
func TestAllProviderErrorCodes_ReturnsAll10(t *testing.T) {
	codes := AllProviderErrorCodes()
	if len(codes) != 10 {
		t.Errorf("AllProviderErrorCodes: want 10 codes, got %d", len(codes))
	}
	for _, c := range codes {
		if !IsValidProviderErrorCode(c) {
			t.Errorf("AllProviderErrorCodes returned invalid code %q", c)
		}
	}
}

// TestIsValidProviderErrorCode exercises the validation helper
// for both valid and unknown codes.
func TestIsValidProviderErrorCode(t *testing.T) {
	if !IsValidProviderErrorCode(ErrorCodeRateLimited) {
		t.Error("ErrorCodeRateLimited should be valid")
	}
	if !IsValidProviderErrorCode(ErrorCodeInternalError) {
		t.Error("ErrorCodeInternalError should be valid")
	}
	if IsValidProviderErrorCode("not_a_real_code") {
		t.Error("unknown string should NOT be a valid code")
	}
	if IsValidProviderErrorCode("") {
		t.Error("empty string should NOT be a valid code")
	}
}
